name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, typecheck, test]
    name: ${{ matrix.script }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Run ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}
